language: ruby
rvm:
 - 2.2

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
  - master
  - develop

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && rsync --rsh='sshpass -p $DEPLOY_PASS ssh -l $DEPLOY_USER' ./_site/ $DEPLOY_HOST:$DEPLOY_PATH/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: "sSLnFJC7yP0Sl8oRbfy3mFRuh2/F6Gc6bNm2+s1ueMjKKswmVtSn3CoBx8s8XIHulABWltO8w8RfWSffs1c2JynMMjC9t7CKfuqNwJpLfArvpEEa4fAzWcep8b7s9FIX0FP/xTzf7JXehvbgwhHCzsBYkp5S0z2xogmw9vlHmBY0OMsiMrOhUiwnqEElOExAMdOECINto4T07yD61PNVbOvEyQPCRwCqGrGtevs7t/DwM5N38Uw4aY+p8VmCbAMbV9bxbYYsWHocWfVHoRBkuvdu95JBj0Rj8isuXfq/CdKDpWPHs1BNYoAgiJuLKVGmIzSO2tbFIlnkxv264uVOyzoFdVV6oBZcPZZB43gebbROcU54Wy6Lq6BqV2T6vWqRhXhi8H08+P/UmwIDvhOvYH0HnFWOadXkyLt0Ou1gjKN4jVzDzfu8yA7Ro5ywA6AtpSFZlUXTGRkTp8NTcpxdBMqelBhiOIMFVOzPE7xSM50nzP/rE8jyeRR7+WG7AmEAM2gyjO161MLkx/YOg/GRwPHGwz21lwYq94fu/9l0wEb0Pf2Hu8hfhg9MCb5FZZQj10d+fbbleGflvU4m/SD6UYeLMkwwuhKtHd4BB6ZcPQa600+pwD8PwMVki6/uxA7nB5fWARd63tAdb2HddoF2vXuyph0OIzeS1uUOBmV8K8U="
  - secure: "tE0HXv+ywmLMBKEEhLmgn/tGVWE2Y3ePOkcAjNd3TyAvxcz5NRH5hwpXHfvwBOqSXVwXkv6LuFTStbVWrYvtu7omSkToDUmQrn/KENN0knaR9FH+vP+w0glbLA2N+tThnETJOSeeq2psR5mZ8SZA/apGPkTcl9u8Su0DW7YEggAqCcGZ+qU81Yr/sNb0luwKZeU2X5C9W4Db5nQMf8twQdi9sd5X7AMo8mOR+h0rr23ATIT7/3X4540p4YWwT0LasY8fw6XLvqVthDkaO63I+Qmiutu1YRXBfbkK6DSNHVnAIjnyQ0GCFoJv3AQTl2WFkSY4kG2D2J97wCHSYGZYat5NX1h47wkk3G44n7d1wPKN2yFkEL2Cptka7N5+fBSP75j/iNsxbuN6QN/anerFsuhAU27ZLJ2B5GmxlFDwbyvkYS+Yf+UEHq5+jgf06yqF3qg10GdB0rn1FIPWV31AvvEVaLzhZtmuhQ+nzRLjLrfdLOutEEFUSb/1s1GbrtSUZDrqRPcstOJsdTIlL3rVL04C5ga51QTgfpJJjZa4f3W1qRUr1sc2l3oLyLuG9ac0bynJAD+Edwy/3RPEEigue9rPxH2MvD7uDqH86wxdwlM8NWBtIw6drHZZzALt2H6AiSGaacBpdUvcsWUUat/6JaKxVpr7vdMdl5QdQMjUwaU="
  - secure: "OsgiSxKJE9U8hl3UtrHfFPE9qyc4JRdiemsl+398fE4XfCGDtgZTg31xNK5Vy+lkDYRme8kij9ehrMDghvsvqEfAP1XTTr4xZcDzvErNee76psO2ejTEF/VP7tKPi7Uf9CBEekxR6MYqOeMrjj38B4Je/di26eAu2uMlI2yDmzWQ7yX67NO4V9hqurQxViG2BEKWgMmGgTKSY9VpBHpErGobnyNws4r6JM4pSGyFw6AiDyo9g24On36Bmmu3k8i1+8EcSfZhmWEbbUjAhTzvz0CNQ7jhFw18izWLM/HcM4Vcx0UwsViNV2gCM9k8LA/kyDkbEpV+COJP0jdjWHy3UxfREyI+olBtESYLL42TbnQs68TmABN9nnNMgUXPg/2pH5k3q1fyMKruu14WkoNca5HYWgUqpoFp6peAzLd8GWZ0auRe0G/YoJfZFEHcltrtXWGoeTAcO98TJWQGiRKTme199SatG6Q+LbakZC2pTbMFU98/DLPit23680cqD5IN/BJYR0v4R/1LuRS1xBuVA4vYqna677FwNYVX/QIUsdTy29MhZwh1ggmxbnd+cRz5p1zf1mHDrib1Kiwsg4grVsOY467CWeuIlqoN/pEj4QPNAvZkiUhZJsuAEMNLOjGV8Nr2TyqIvitC8nRVxV8iKKovv6k79QqxBuq3uxCO1Ao="
  - secure: "Fs86VcZ2ZK6AImdqXMTCvEtG4wDcGNfDinDIBrreUYlqI5i8eoTLy7IeyEt2+7wiCJQkWv5vi6XWcFxK91QKsrhMxItwBlfriIwt2YDdel0iMT1lkfZKWvX0jJvknDcTDQl3SIh4ZFNuw/8qBrHI30d2biUuRbIWyci1FRL48BQc+xB2PK9B3yVQv5+ciZzb947q+C3C70Id99NkkLtjA3myuHbcclICPA0o6J+ES0CK/WYMlwvjgUbBONSQ3REh4c/j+yyN2BUnOtmOrx81fP2nP1MeuASddGE/MkjQkHFyzq9krhZKcDZOVbMkQ9eMnjpnqJlW6x1fnl4WgzHIRVXLsDLWNGr0eLMZi3WAqpReAN5+fx6y+DSb7TjO/oJMQsbsnPi1MgKakRgkhCipyK5GNeEkGDW2uA8UpaZ/CX9FxAx3miNMJGxt6lO3hNgE9iAsfAc2F0iuR6TlHtFElO6ADTTxxiQ3PVueKJtN8iCYYHID/HFHH5Qktb/hZoYXG2GCFGsgOMT9W7CVkeDXxKP0Z7Yk9FyNJTh/XLuExgv5prz8HEdtUzTfMZbgOJJNCN3DxfKieFYuCQ3BHrAX3h6Z70C6uyiC2YL/7/yAYmt+m4ZQRNPogrgWlNNCnGWv60f9VJDQTLT+oeCPx1eNWqp5QLWKVJ1CqVqXWL4Ng44="

addons:
  apt:
    packages:
      - sshpass
