language: ruby
rvm:
 - 2.2

addons:
 - ssh_known_hosts: 163.225.10.59

before_install:
 - openssl aes-256-cbc -K $encrypted_bd7094889ad8_key -iv $encrypted_bd7094889ad8_iv -in deploy_rsa.enc -out deploy_rsa -d

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

before_deploy:
 - eval "$(ssh-agent -s)"
 - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
 - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site/ www-ime@163.225.10.59:public_html/
#   on:
#     branch: master
