# Site settings
title: '岡山県立大学情報工学部情報通信工学科 知能メディア工学研究室'
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www-ime.c.oka-pu.ac.jp" # the base hostname & protocol for your site
exclude: [script, .git, .gitignore]
timezone: 'Asia/Tokyo'
permalink: date

# Build settings
markdown: kramdown
